####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include_dir_merge_named customize/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/conversation/
conversation:

#https://www.home-assistant.io/components/discovery/
#Disabled for now
#discovery:

#https://www.home-assistant.io/components/frontend/
frontend:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123 #reserved for future use (will need secret)

#https://home-assistant.io/components/logbook/
logbook:

#https://home-assistant.io/components/logger/
logger:
  default: error
  logs:
    homeassistant.components.sensor.template: critical

#https://www.home-assistant.io/components/map/
map:

#https://home-assistant.io/components/recorder/
recorder:
  purge_interval: 1
  purge_keep_days: 3

#https://www.home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/tts/
tts:
  - platform: google

#https://www.home-assistant.io/components/updater/
#Keeping this until I finish the notification flow using the current verison check via REST
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
light: !include lights.yaml
notify: !include notifications.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

####################################################
#                                                  #
#                SESAME SMART LOCK                 #
#                                                  #
####################################################

lock:
  - platform: sesame
    email: nperanzi@gmail.com
    password: !secret sesame_password

####################################################
#                                                  #
#                KODI MEDIA PLAYER                 #
#                                                  #
####################################################

media_player:
  - platform: kodi
    host: 192.168.1.151

####################################################
#                                                  #
#                HARMONY HUB REMOTE                #
#                                                  #
####################################################

remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.102
    activity: Kodi

####################################################
#                                                  #
#                     ZWAVE                        #
#                                                  #
####################################################

#https://home-assistant.io/docs/z-wave/
zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
