####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization files
  customize: !include_dir_merge_named customize/
  packages: !include_dir_named packages

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/conversation/
conversation:

#https://www.home-assistant.io/components/discovery/
#Disabled for now
discovery:

#https://www.home-assistant.io/components/frontend/
frontend:

#https://home-assistant.io/components/history/
history:
  include:
    domains:
      - switch
      - media_player
      - remote
    entities:
      - group.nick
      - group.rachel
      - binary_sensor.ecolink_doorwindow_sensor_sensor
      - sensor.installed_version
      - sensor.latest_version
      - sensor.us_air_pollution_level
      - sensor.last_boot
      - sensor.fast_com_download
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sun.sun
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_pressure
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.processor_use
      - sensor.cpu_temperature

#https://home-assistant.io/components/http/
http:
  base_url: !secret base_url

#https://home-assistant.io/components/logbook/
logbook:

#https://home-assistant.io/components/logger/
logger:
  default: error
  logs:
    homeassistant.components.sensor.template: critical
    homeassistant.components.stream: debug

#https://www.home-assistant.io/components/map/
map:

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://home-assistant.io/components/recorder/
recorder:
  purge_interval: 1
  purge_keep_days: 3

#https://www.home-assistant.io/components/stream/
stream:

#https://www.home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    service_name: google_say

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
notify: !include notifications.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell_commands.yaml
switch: !include switches.yaml

####################################################
#                                                  #
#                   AIRVISUAL                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/sensor.airvisual/
airvisual:
  api_key: !secret airvisual_api
  geographies:
    latitude: !secret latitude
    longitude: !secret longitude

####################################################
#                                                  #
#                   FASTDOTCOM                     #
#                                                  #
####################################################

#https://www.home-assistant.io/components/fastdotcom/
fastdotcom:
  scan_interval:
      minutes: 30

####################################################
#                                                  #
#            IQVIA (FORMERLY POLLEN.COM)           #
#                                                  #
####################################################

#https://www.home-assistant.io/components/iqvia/

iqvia:
  zip_code: !secret zipcode

####################################################
#                                                  #
#                 JOAOAPPS (JOIN)                  #
#                                                  #
####################################################

#https://www.home-assistant.io/components/joaoapps_join/

joaoapps_join:
  - name: Join_Android
    device_id: group.android
    api_key: !secret join_api

####################################################
#                                                  #
#                     LOVELACE                     #
#                                                  #
####################################################

#https://www.home-assistant.io/lovelace/yaml-mode/

lovelace:
  mode: yaml

####################################################
#                                                  #
#                   PHILIPS HUE                    #
#                                                  #
####################################################

#https://www.home-assistant.io/components/hue/

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true

####################################################
#                                                  #
#                SESAME SMART LOCK                 #
#                                                  #
####################################################

#https://www.home-assistant.io/components/lock.sesame/

#lock:
#  - platform: sesame
#    api_key: !secret sesame_api

####################################################
#                                                  #
#                SPEEDTESTDOTNET                   #
#                                                  #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

####################################################
#                                                  #
#                     SPOTIFY                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/spotify/

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

####################################################
#                                                  #
#                     TP-LINK                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/tplink/

tplink:

####################################################
#                                                  #
#                     ZWAVE                        #
#                                                  #
####################################################

#https://home-assistant.io/docs/z-wave/

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################

