#https://www.home-assistant.io/lovelace/yaml-mode/

####################################################
#                                                  #
#                     LOVELACE                     #
#                                                  #
####################################################

title: Home
views:
  - badges: []
    cards:
      - elements:
          # 3D Printer
          - entity: switch.3d_printer
            style:
              font-size: 10px
              left: 72.5%
              top: 27.5%
            type: state-icon
          - entity: light.side_light
            style:
              font-size: 10px
              left: 75.5%
              top: 27.5%
            type: state-icon
          # Air Purifier
          - entity: fan.living_room_air_purifier
            style:
              font-size: 10px
              left: 30%
              top: 67.5%
            type: state-icon
          # Badges across top row
          - entity: group.nick
            style:
              font-size: 10px
              left: 20%
              top: 10%
            type: state-badge
          - entity: group.rachel
            style:
              font-size: 10px
              left: 40%
              top: 10%
            type: state-badge
          - entity: input_boolean.vacation
            style:
              font-size: 10px
              left: 60%
              top: 10%
            type: state-badge
          - entity: input_boolean.guest
            style:
              font-size: 10px
              left: 80%
              top: 10%
            type: state-badge  
          # Brother printer
          - entity: sensor.dcp_l2550dw_status
            style:
              left: 21%
              top: 27.5%
            type: state-icon
            tap_action:
              action: more-info 
          # Climate Controls        
          #- entity: climate.living_room_hvac
          #  icon: 'mdi:air-conditioner'
          #  style:
          #    left: 21%
          #    top: 47.5%
          #  tap_action:
          #    action: more-info
          #  type: icon
          #- entity: sensor.living_room_hvac_desc
          #  style:
          #    left: 21%
          #    top: 52.5%
          #  type: state-label
          #- entity: climate.kitchen_hvac
          #  icon: 'mdi:air-conditioner'
          #  style:
          #    left: 43.5%
          #    top: 70%
          #  tap_action:
          #    action: more-info
          #  type: icon
          #- entity: sensor.kitchen_hvac_desc
          #  style:
          #    left: 43.5%
          #    top: 75%
          #  type: state-label
          #- entity: climate.nursery_hvac
          #  icon: 'mdi:air-conditioner'
          #  style:
          #    left: 67.5%
          #    top: 35%
          #  tap_action:
          #    action: more-info
          #  type: icon
          #- entity: sensor.nursery_hvac_desc
          #  style:
          #    left: 67.5%
          #    top: 40%
          #  type: state-label
          #- entity: climate.bedroom_hvac
          #  icon: 'mdi:air-conditioner'
          #  style:
          #    left: 87.5%
          #    top: 62.5%
          #  tap_action:
          #    action: more-info
          #  type: icon
          #- entity: sensor.bedroom_hvac_desc
          #  style:
          #    left: 87.5%
          #    top: 67.5%
          #  type: state-label
          # Lights
          - entity: light.bedroomlamp
            hold_action:
              action: more-info
            style:
              left: 92.5%
              top: 75%
            tap_action:
              action: toggle
            type: state-icon
          # Lock
          - entity: lock.august_smart_lock
            state_color: false
            style:
              left: 45%
              top: 44%
            tap_action:
              action: toggle
            type: state-icon
          # Vacuum
          - entity: vacuum.e200p8u2391901643307
            icon: 'mdi:robot-vacuum'
            style:
              left: 12.5%
              top: 67.5%
            tap_action:
              action: toggle
            type: state-icon
        image: /local/images/floorplan/home2020-v02.png
        type: picture-elements
#      - type: weather-forecast
#        entity: weather.kbos_daynight
#      - entities:
#          - sensor.dark_sky_summary
#          - sensor.dark_sky_hourly_summary
#          - sensor.dark_sky_temperature
#          - sensor.dark_sky_apparent_temperature
#          - sensor.dark_sky_wind_speed
#          - sensor.dark_sky_humidity
#          - sensor.dark_sky_uv_index
#          - sun.sun
#          - sensor.dark_sky_visibility
#          - sensor.dark_sky_daily_summary
#        show_header_toggle: false
#        title: Weather Summary
#        type: entities
#      - entity: climate.living_room_hvac
#        name: AC Control
#        theme: default
#        type: thermostat
    icon: 'mdi:home'
    panel: true
    path: home
    title: Home
  - title: Weather
    path: weather
    panel: false
    icon: 'mdi:weather-cloudy'
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.kbos_daynight
  - badges: []
    cards:
      - entities:
          - entity: sensor.processor_use
          - entity: sensor.disk_use_percent_home
          - entity: sensor.memory_use_percent
          - entity: sensor.last_boot
          - entity: sensor.cpu
          - entity: sensor.cpu_temperature
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.ha_uptime
        show_header_toggle: false
        title: Server Monitor
        type: entities
      - entities:
          - entity: sensor.installed_version
          - entity: sensor.latest_version
        show_header_toggle: false
        title: HA Version Info
        type: entities
      - entities:
          - entity: sensor.fast_com_download
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_ping
        show_header_toggle: false
        title: Network Monitor
        type: entities
      - entities:
          - entity: switch.adguard_filtering
          - entity: switch.adguard_safe_browsing
          - entity: switch.adguard_safe_search
          - entity: switch.adguard_parental_control
          - entity: sensor.adguard_dns_queries
          - entity: sensor.adguard_dns_queries_blocked_ratio
          - entity: sensor.adguard_average_processing_speed
        show_header_toggle: false
        title: AdGuard Home
        type: entities
    icon: 'mdi:home-automation'
    path: system
    title: System
  - badges: []
    cards:
      - entities:
          - entity: automation.set_foscam_to_away_mode_when_no_one_is_home
          - entity: automation.set_foscam_to_home_mode_when_someone_is_home
          - entity: automation.lock_front_door_at_830pm
          - entity: automation.lock_front_door_at_night
          - entity: automation.lock_front_door_after_we_leave
          - entity: automation.turn_on_lights_when_we_come_home
        show_header_toggle: false
        title: Security
        type: entities
      - entities:
          - entity: automation.home_assistant_update_notifier
          - entity: automation.front_door_open_notifications
          - entity: automation.front_door_unlocked_notifications
          - entity: automation.rachel_workday_weather_details
        show_header_toggle: false
        title: Notifications
        type: entities
      - entities:
          - entity: script.foscam_off
          - entity: script.foscam_on
          - entity: script.weather_briefing
          - entity: script.weather_briefing_wife
        show_header_toggle: false
        title: Scripts
        type: entities
      - entities:
          - entity: input_boolean.disable_daily_vacuum
          - entity: input_boolean.disable_dustbin_notification
          - entity: input_boolean.daily_vacuum_first_run
          - entity: sensor.ecovacs_vacuum_cleaner_status
          - entity: automation.reset_daily_vacuum_first_run_state_at_midnight
          - entity: automation.send_alert_after_daily_vacuum_to_empty_the_dustbin
          - entity: automation.start_daily_vacuum
        show_header_toggle: false
        title: Vacuum
        type: entities
    path: automations
    title: Automations

####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################
