#https://www.home-assistant.io/lovelace/yaml-mode/

####################################################
#                                                  #
#                     LOVELACE                     #
#                                                  #
####################################################

title: Mobile
views:
  - title: Rooms
    badges: []
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: lock.august_smart_lock
        name: Front Door
        show_state: true
      - type: vertical-stack
        title: Living Room
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.lr_front_light_switch_level
                name: Sitting Area
              - type: light
                entity: light.lr_back_light_switch_level
                name: Office Area
              - type: light
                entity: light.hallway_lights
                name: Hallway
          - type: 'custom:custom-fan-card'
            entity: fan.lr_fan_switch_level
            name: Living Room Fan
          - type: thermostat
            entity: climate.living_room_hvac
          - type: 'custom:xiaomi-vacuum-card'
            entity: vacuum.e200p8u2391901643307
            name: Bird Legs
            vendor: ecovacs
          - type: media-control
            entity: media_player.shield_2
      - type: vertical-stack
        title: Bedroom
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bedroomlamp
                name: Side Light
              - type: light
                entity: light.bedroom_fan
                name: Overhead
              - type: light
                entity: light.b_closet_light_switch_level
                name: Closet
              - type: light
                entity: light.bedroom_hallway_lights
                name: Entryway
          - type: 'custom:custom-fan-card'
            entity: fan.bedroom_fan
            name: Bedroom Fan
          - type: thermostat
            entity: climate.bedroom_hvac
          - type: media-control
            entity: media_player.shield
      - type: vertical-stack
        title: Nursery
        cards:
          - type: horizontal-stack 
            cards:
              - type: light
                entity: light.n_light_switch_level
                name: Overhead
              - type: light
                entity: light.side_light
                name: Printer Light
              - type: button
                tap_action:
                  action: toggle
                entity: switch.3d_printer
                show_state: false
                name: Printer Power
          - type: thermostat
            entity: climate.nursery_hvac
      - type: vertical-stack
        title: Kitchen
        cards:
          - type: horizontal-stack 
            cards:
              - type: light
                entity: light.k_counter_light_switch_level
                name: Counter
              - type: light
                entity: light.k_table_light_switch_level
                name: Table
          - type: thermostat
            entity: climate.kitchen_hvac


####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################
