####################################################
#                                                  #
#               AUTO-LOCK AT NIGHT                 #
#                                                  #
####################################################

  - alias: Lock front door at night
    trigger:
      platform: state
      entity_id: lock.peranzi
      to: 'unlocked'
      for:
        hours: 0
        minutes: 30
    condition:
      condition: time
      after: '20:30:00'
      before: '05:30:00'
    action:
      service: lock.lock
      entity_id: lock.peranzi

####################################################
#                                                  #
#              AUTO-LOCK AT 8:30 PM                #
#                                                  #
####################################################

  - alias: Lock front door at 830pm
    trigger:
      platform: time
      at: '20:30:00'
    action:
      service: lock.lock
      entity_id: lock.peranzi

####################################################
#                                                  #
#           AUTO-LOCK IF NO ONE IS HOME            #
#                                                  #
####################################################

  - alias: Lock front door after we leave
    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
    condition:
      condition: state
      entity_id: lock.peranzi
      state: 'unlocked'
    action:
      service: lock.lock
      entity_id: lock.peranzi

####################################################
#                                                  #
#                FRONT DOOR OPENED                 #
#                                                  #
####################################################

  - alias: 'Front door open notifications'
    trigger:
    - entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        message: 'The front door was opened at {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
        title: Front Door Opened
      service: notify.join

####################################################
#                                                  #
#                FRONT DOOR UNLOCKED               #
#                                                  #
####################################################

  - alias: 'Front door unlocked notifications'
    trigger:
    - entity_id: lock.peranzi
      from: 'locked'
      platform: state
      to: 'unlocked'
    action:
    - data:
        message: 'The front door was unlocked at {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
        title: Front Door Unlocked
      service: notify.join

####################################################
#                                                  #
#                FOSCAM DIS/ENABLE                 #
#                                                  #
####################################################

  - alias: Set Foscam to Away Mode when no one is home
    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
    action:
      service: script.foscam_on
  - alias: Set Foscam to Home Mode when someone is home
    trigger:
      platform: state
      entity_id: group.family
      to: 'home'
    action:
      service: script.foscam_off

####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################

