####################################################
#                                                  #
#               AUTO-LOCK AT NIGHT                 #
#                                                  #
####################################################

  - alias: Lock front door at night
    trigger:
      platform: time
      at: '20:30:00'
    action:
      - service: lock.lock
        entity_id:
          - lock.peranzi

####################################################
#                                                  #
#           AUTO-LOCK IF NO ONE IS HOME            #
#                                                  #
####################################################

  - alias: Lock front door after we leave
    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 5
    action:
      - service: lock.lock
        entity_id:
          - lock.peranzi

####################################################
#                                                  #
#                FRONT DOOR OPENED                 #
#                                                  #
####################################################

  - alias: 'Front door open notifications'
    trigger:
    - entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        message: 'The front door was opened at {{ states.sensor.time_date.date_time.state }}'
        title: Front Door Opened
      service: notify.join

####################################################
#                                                  #
#                FOSCAM DIS/ENABLE                 #
#                                                  #
####################################################

  - alias: Set Foscam to Away Mode when no one is home
    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
    action:
      service: script.foscam_on
  - alias: Set Foscam to Home Mode when someone is home
    trigger:
      platform: state
      entity_id: group.family
      to: 'home'
    action:
      service: script.foscam_off

####################################################
#                                                  #
#           END OF CONFIGURATION FILE              #
#                                                  #
####################################################

