###############################################################################
#   @author         :   Nick Peranzi
#   @date           :   2021-02-20
#   @package        :   Roborock S4 Max Robot Vacuum
#   @description    :   Roborock Robot Vacuum Control and Schedule
###############################################################################
homeassistant:
  customize:
    input_boolean.disable_daily_vacuum:
      icon: mdi:stop-circle-outline
    input_boolean.disable_dustbin_notification:
      icon: mdi:delete-empty

group:
  Robot Vacuum:
    entities:
      - vacuum.s4_max
      - input_boolean.disable_daily_vacuum

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: off
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: off
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: off
  vacuum_notification_sent:
    name: Vacuum Notification Sent
    initial: off

sensor:
  - platform: template
    sensors:
      ecovacs_vacuum_cleaner_status:
        entity_id:
          - vacuum.s4_max
        friendly_name: "Ecovacs Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.vacuum.s4_max }}"

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_host
    token: !secret xiaomi_token
    name: S4 Max

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Start Daily Vacuum
    trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 20
    - platform: time
      at: '09:05:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.daily_vacuum_first_run
        state: 'off'
      - condition: time
        after: '09:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.disable_daily_vacuum
        state: 'off'
    action:
    - delay: '00:00:30'
    - service: vacuum.turn_on
      entity_id: vacuum.s4_max
    - service: homeassistant.turn_on
      entity_id: input_boolean.daily_vacuum_first_run

  - alias: Reset Daily Vacuum First Run state at midnight
    trigger:
    - platform: time
      at: '0:00:00'
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.daily_vacuum_first_run
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacuum_notification_sent

  - alias: Send alert after daily vacuum to empty the dustbin
    trigger:
    - platform: state
      entity_id: group.family
      to: 'home'
      for:
        minutes: 2
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.daily_vacuum_first_run
        state: 'on'
      - condition: time
        after: '08:30:00'
        before: '22:30:00'
      - condition: template
        value_template: >
          {% if states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.attributes.last_triggered) | int > 1800 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
      - condition: state
        entity_id: input_boolean.disable_dustbin_notification
        state: 'off'
      - condition: state
        entity_id: input_boolean.vacuum_notification_sent
        state: 'off'
    action:
      - service_template: >
          {% if (is_state('group.nick', 'home')) and (is_state('group.rachel', 'home'))  %}
            notify.hangouts_all
          {% elif is_state('group.nick', 'home') %}
            notify.hangouts
          {% elif is_state('group.rachel', 'home') %}
            notify.hangouts_wife
          {% endif %}
        data:
          message: 'Hey, the vacuum dustbin needs to be cleared'
          title: 'Vacuum Dustbin'
      - service: homeassistant.turn_on
        entity_id: input_boolean.vacuum_notification_sent