###############################################################################
#   @author         :   Nick Peranzi
#   @date           :   2021-02-20
#   @package        :   Roborock S4 Max Robot Vacuum
#   @description    :   Roborock Robot Vacuum Control and Schedule
###############################################################################
homeassistant:
  customize:
    input_boolean.disable_daily_vacuum:
      icon: mdi:stop-circle-outline
    input_boolean.disable_dustbin_notification:
      icon: mdi:delete-empty

group:
  Robot Vacuum:
    entities:
      - vacuum.s4_max
      - input_boolean.disable_daily_vacuum

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: off
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: off
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: off
  vacuum_notification_sent:
    name: Vacuum Notification Sent
    initial: off

sensor:
  - platform: template
    sensors:
      ecovacs_vacuum_cleaner_status:
        entity_id:
          - vacuum.s4_max
        friendly_name: "S4 Max Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.vacuum.s4_max }}"

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_host
    token: !secret xiaomi_token
    name: S4 Max
